<Workspace Version="0.7.2.2921" X="0" Y="0" zoom="1" Description="" Category="" Name="Home">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="7b0fcaf7-d52c-4b50-bc93-dfa7275683fc" nickname="Python Script" x="323" y="74.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
clr.AddReference('AsNodes')
from Autodesk.DesignScript.Geometry import *
from AsNodes import *
#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN[0]
pt = Point.ByCoordinates(dataEnteringNode.X,dataEnteringNode.Y,dataEnteringNode.Z+1000)
beam = AsStraightBeam.ByStartPointEndPoint(dataEnteringNode,pt)
#Assign your output to the OUT variable
OUT = [beam]</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="8b8ff0bf-8a7f-4976-95a9-c4b7c4e89f10" nickname="Point.ByCoordinates" x="134" y="89.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DoubleInput type="Dynamo.Nodes.DoubleInput" guid="6da0969b-a88e-4c03-8b35-f83d1995e710" nickname="Number" x="30" y="96.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double value="100" />
    </Dynamo.Nodes.DoubleInput>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="8b8ff0bf-8a7f-4976-95a9-c4b7c4e89f10" start_index="0" end="7b0fcaf7-d52c-4b50-bc93-dfa7275683fc" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6da0969b-a88e-4c03-8b35-f83d1995e710" start_index="0" end="8b8ff0bf-8a7f-4976-95a9-c4b7c4e89f10" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6da0969b-a88e-4c03-8b35-f83d1995e710" start_index="0" end="8b8ff0bf-8a7f-4976-95a9-c4b7c4e89f10" end_index="1" portType="0" />
  </Connectors>
  <Notes />
</Workspace>